# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatmap', '0002_load_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipv6address',
            name='latitude',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='ipv6address',
            name='longitude',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
